### ISSUE TITLE
能否转换npm包内使用的styled-component

### ISSUE THREAD

**Issue by vdfor** [xuyuanxiang/babel-plugin-styled-components-px2rem#1]
如果npm包使用的styled-component，并以px为单位，当我在项目引用此npm包时，使用babel-plugin-styled-components-px2rem并不能对npm包内的px进行转换。

**Comment by xuyuanxiang** [comment]
如果第三方npm包的代码是使用这个插件：[babel-plugin-styled-components](https://styled-components.com/docs/tooling#babel-plugin) 编译过的就不支持了。

比如npm包源码是：
```jsx
export const StyledButton = styled.button`
  width: 120px;
  height: 32px;
  font-size: 14px;
`;
```

用[babel-plugin-styled-components](https://styled-components.com/docs/tooling#babel-plugin)编译后会变成：

```js
export const StyledButton = /*#__PURE__*/styled.button.withConfig({
  displayName: "src__StyledButton",
  componentId: "sc-11sun46-5"
})(["width:120px;height:32px;font-size:14px;"]);
```

这种语法，我写的插件不能处理。

这也是[Composition](https://github.com/xuyuanxiang/babel-plugin-styled-components-px2rem#composition)叙述的：如果要和[babel-plugin-styled-components](https://styled-components.com/docs/tooling#babel-plugin) 一起工作，需要把我写的插件放到这个插件之前，先处理代码的原因。

目前受支持的语法就是[Transform Runtime][https://github.com/xuyuanxiang/babel-plugin-styled-components-px2rem#transform-runtime]中列的这些。


如果第三方npm包的代码未经[babel-plugin-styled-components](https://styled-components.com/docs/tooling#babel-plugin) 处理过，那就可以。

如果使用`@babel/cli`命令行工具编译，配好插件后把输入文件指向node_modules里的某个包的代码文件即可：
```npm
babel node_modules/path/to/file.js --out-dir dist/
```

如果是使用`webpack`、`rollup`这些打包工具，在`include`中加入：`/node_modules/`，如果`exclude`中有node_modules，则去除。  这些打包工具在编译代码时，就会连引入的node_modules中npm包的代码文件一起处理的。

**Comment by vdfor** [comment]
> > 如果npm包使用的styled-component，并以px为单位，当我在项目引用此npm包时，使用babel-plugin-styled-components-px2rem并不能对npm包内的px进行转换。
> 
> 所有模板字符串中的css文本都能转换。
> 
> 对于嵌套在模板字符串中的表达式，如果npm包中的代码使用[babel-plugin-styled-components](https://styled-components.com/docs/tooling#babel-plugin)编译构建的，就不支持了。
> 
> 比如npm包源码是：
> 
> ```js-jsx
> import styled from 'styled-components';
> 
> export const StyledButton = styled.button`
>   width: 120px;
>   height: 32px;
>   font-size: 14px;
>   padding: ${props => props.theme.padding}px;
> `;
> ```
> 
> 该npm包在发布到npm仓库前，使用[babel-plugin-styled-components](https://styled-components.com/docs/tooling#babel-plugin)编译源码，就会被转换成：
> 
> ```js
> import styled from 'styled-components';
> export const StyledButton = /*#__PURE__*/styled.button.withConfig({
>   displayName: "src__StyledButton",
>   componentId: "sc-11sun46-0"
> })(["width:120px;height:32px;font-size:14px;padding:", "px;"], props => props.theme.padding);
> ```
> 
> 如果将上面转换后的代码发布到npm仓库，并且你安装下来，再用`styled-components-px2rem`插件去编译，就会把上面的代码转成：
> 
> ```js
> import styled from 'styled-components';
> export const StyledButton = /*#__PURE__*/styled.button.withConfig({
>   displayName: "src__StyledButton",
>   componentId: "sc-11sun46-0"
> })(["width:1.2rem;height:0.32rem;font-size:0.14rem;padding:", "px;"], props => props.theme.padding);
> ```
> 
> 最终，只转换了字符串中的css文本，但最后这个表达式：`${props => props.theme.padding}px` 无法处理。
> 
> 不论是用`styled-components-px2rem`编译工程内部的源码，还是编译node_modules中第三方依赖的代码，目前受支持的语法就是[Transform Runtime](https://github.com/xuyuanxiang/babel-plugin-styled-components-px2rem#transform-runtime)中列举的这些。
> 
> 另外，[Composition](https://github.com/xuyuanxiang/babel-plugin-styled-components-px2rem#composition)有叙述，在你的工程内部如果需要和[babel-plugin-styled-components](https://styled-components.com/docs/tooling#babel-plugin) 一起工作，需要把`styled-components-px2rem`配置到它前面，在它之前先处理源码。
> 
> 最后，还有关于px2rem一般是用在移动端高清方案，涉及“转换汇率”的问题。
> 
> 如果大家都采用相同的高清方案，比如[umi-hd](https://github.com/umijs/umi-hd)基于相同基准值，那么将node_modules中的代码一起纳入编译范围一起构建即可。
> 
> 如果大家都采用相同的高清方案，但是设计稿基准值不同，比如用750或者640，在将node_modules中代码纳入进来时，需要配2套参数。以`webpack`为例，需要配置2个`babel-loader`，一个处理工程内部的源码，一个处理node_modules目录下的代码。
> 
> 如果npm包采用的高清方案不同，基准值不同，设计稿尺寸不同，html节点上的font-size也不同，转成rem时，就完全无法在同一个HTML页面内正常显示。

似乎有点问题，我试了下安装了使用`styled-components`的第三方组件库，自己也在本地写了个简单的用于测试，发现在项目中引入时，`node_modules`里的并未转换。另外，我发现`exclude`配置并未生效，这一点很奇怪，应该是传入`postcss-plugin-px2rem`了，但结果似乎无效。

最小化可复现仓库： https://github.com/vdfor/css-in-js-issues-demo/tree/master/sc-with-px2rem

**Comment by xuyuanxiang** [comment]
@vdfor 还是上面说到的问题，`babel-plugin-styled-components-px2rem`插件目前还不支持处理被[babel-plugin-styled-components](https://styled-components.com/docs/tooling#babel-plugin)插件编译过的代码。

在你的demo中引入的`@kiwicom/orbit-components/s/Button`就是被[babel-plugin-styled-components](https://styled-components.com/docs/tooling#babel-plugin)编译后的，[babel-plugin-styled-components](https://styled-components.com/docs/tooling#babel-plugin)会加上：`withConfig()`，这种语法还识别不了：

![](https://cdn.xuyuanxiang.me/issue_f683c2c3.png)

这个问题，我研究下看怎么支持转换被[babel-plugin-styled-components](https://styled-components.com/docs/tooling#babel-plugin)编译过的代码。

另外，关于umi， 可以在`chainWebpack`配置项中，在通过`console.log`打印：

```typescript
import { defineConfig } from 'umi';

export default defineConfig({
  alias: {
  },
  chainWebpack(config) {
    // console.log('rules:', config.module.rules.get('js').exclude.values());
    config.module.rules.get('js').exclude.clear();
  },
  extraBabelPlugins: [
    [
      'styled-components-px2rem',
      {
        rootValue: 32,
        unitPrecision: 5,
        minPixelValue: 0,
        multiplier: 1,
        transformRuntime: true,
        exclude: /![\\/]node_modules[\\/]/ // 指定为 node_modules目录
      },
    ],
  ],
  routes: [{ path: '/', component: '@/pages/index' }],
});
```

可以发现控制台输出：
![](https://cdn.xuyuanxiang.me/exclude_23f48c04.png)

即umi的babel-loader exclude配置了：`/node_modules/`，所以umi中的babel不会编译`/node_modules/`中的代码。

用`webpack-chain`的API 调`clear`方法把exclude清空就行了。

**Comment by xuyuanxiang** [comment]
`babel-plugin-styled-components-px2rem`不适用于处理`node_modules`中的第三方styled-components组件。

原因：

1. 第三方依赖在打包发布到NPM前，基本都会用[babel-plugin-styled-components](https://styled-components.com/docs/tooling#babel-plugin)去编译他们的源码，所以发布到NPM的包里都是被[babel-plugin-styled-components](https://styled-components.com/docs/tooling#babel-plugin)处理后的代码，`babel-plugin-styled-components-px2rem`无法处理这种被编译后的代码。

2. styled-components模板字符串通常都会嵌套表达式（`${expression}`），`babel-plugin-styled-components-px2rem`只会处理以`px`结尾的表达式：`${expression}px`。

关于第2点举个例子，第三方依赖的源码如果是这样：

```typescript
const stringHeight: string = '44px';
const StringHeightButton = styled.button`
  width: 120px;
  height: ${stringHeight}
`;
```

是无法处理的，转换后高度还是：`44px`。 

综述：`babel-plugin-styled-components-px2rem`支持嵌套的表达式，无论是箭头函数，变量引用，还是其他...    这些表达式的共通点就是运行后，返回的结果是 number类型。

**Comment by vdfor** [comment]
> `babel-plugin-styled-components-px2rem`不适用于处理`node_modules`中的第三方styled-components组件。
> 
> 原因：
> 
> 1. 第三方依赖在打包发布到NPM前，基本都会用[babel-plugin-styled-components](https://styled-components.com/docs/tooling#babel-plugin)去编译他们的源码，所以发布到NPM的包里都是被[babel-plugin-styled-components](https://styled-components.com/docs/tooling#babel-plugin)处理后的代码，`babel-plugin-styled-components-px2rem`无法处理这种被编译后的代码。
> 2. 第三方依赖发布到NPM的代码一般都是ES5，模板字符串是ES6语法，已经被babel编译为函数调用，`babel-plugin-styled-components-px2rem`只支持styled-components官网示例的那些写法。
>    有些第三方依赖虽然会同时输出CommonJS和ESModule两种格式的代码，比如有的npm包里有es这样的目录， 但ESModule仅仅是模块的导入导出使用了ES6的`import`和`export`方便做Tree Shaking，其余代码还是ES5。
> 3. styled-components模板字符串通常都会嵌套表达式：`${expression}`，`babel-plugin-styled-components-px2rem`只会处理以`px`结尾的表达式：`${expression}px`。
> 
> 关于第3点举个例子，第三方依赖的源码如果是这样：
> 
> ```ts
> const stringHeight: string = '44px';
> const StringHeightButton = styled.button`
>   height: ${stringHeight}
> `;
> ```
> 
> 是无法处理的，转换后高度还是：`44px`。

明白了，感谢解答，多谢。对于团队内部，自己开发组件库自己用，按照约定来，还是可以使用的。
