### ISSUE TITLE
How to use with create-react-app?

### ISSUE THREAD

**Issue by dan-dr** [xuyuanxiang/babel-plugin-styled-components-px2rem#2]
Very cool plugin but I can't seem to make it work with [react-boilerplate](https://github.com/react-boilerplate/react-boilerplate-cra-template)

I'm using [craco](https://github.com/gsoft-inc/craco/) to change my babel loader.

```
    babel: {
      loaderOptions: {
        plugins: [
          [
            'styled-components-px2rem',
            {
              rootValue: 16,
              unitPrecision: 5,
              minPixelValue: 0,
              multiplier: 1,
              transformRuntime: true,
            },
          ],
       ],
      },
    },
```

but my units stay in px.

Any idea what I can do?

**Comment by xuyuanxiang** [comment]
> Very cool plugin but I can't seem to make it work with [react-boilerplate](https://github.com/react-boilerplate/react-boilerplate-cra-template)
> 
> I'm using [craco](https://github.com/gsoft-inc/craco/) to change my babel loader.
> 
> ```
>     babel: {
>       loaderOptions: {
>         plugins: [
>           [
>             'styled-components-px2rem',
>             {
>               rootValue: 16,
>               unitPrecision: 5,
>               minPixelValue: 0,
>               multiplier: 1,
>               transformRuntime: true,
>             },
>           ],
>        ],
>       },
>     },
> ```
> 
> but my units stay in px.
> 
> Any idea what I can do?

I create a new project: [cra-example](https://github.com/xuyuanxiang/cra-example) according to the boilerplate you provided:

```npm
create-react-app --template cra-template-rb cra-example
```

I use `craco` in this example as well, and it works for me:

![](https://cdn.xuyuanxiang.me/it_works_for_me_7dc48425.png)

You can compare the difference between the initial boilerplate and using craco: 

[compare/0.0.1...1.0.0](https://github.com/xuyuanxiang/cra-example/compare/0.0.1...1.0.0)

**Comment by dan-dr** [comment]
Well I don't know how but it suddenly works. Thanks for the help.
